### ISSUE TITLE
Scores data from ESPN scores API

### ISSUE THREAD

**Issue by aannestrand** [Nickwang3/EE461LProject#21]
Grab recent baseball scores from ESPN and place into database

**Comment by Jombari** [comment]
How recent should the scores be? I'm thinking scores in the current month?

**Comment by Nickwang3** [comment]
Yeah that sounds fine for now.

**Comment by Jombari** [comment]
So the API looks like it pulls the sports for the current day so I may only be able to do the scores and schedule for the current day. But i'll lyk if I can do the whole month.

**Comment by Nickwang3** [comment]
Honestly just the current day seems perfectly fine.

**Comment by aannestrand** [comment]
We are getting scores from a different API
