### ISSUE TITLE
[MVC] Refactor the search abilities into a MVC framework

### ISSUE THREAD

**Issue by aannestrand** [Nickwang3/EE461LProject#93]
The model will be the parent state. The controller will be the search "panel" component. The view will be the components in the parent class that show the state.

**Comment by Nickwang3** [comment]
Cut down on a ton of repeated code doing this. Created controller components for searching/sorting and pagination. Now acts as a MVC where the controllers change the state of the results, and the page displays the results. Took about 3 hrs.
